### ISSUE TITLE
 Transformation error (Cannot read properties of undefined (reading 'length'))

### ISSUE THREAD

**Issue by canpoyrazoglu** [mskelton/ratchet#42]
I'm trying to convert part of a JS codebase to TS and want to automate switching from propTypes to TypeScript.

I've ran the script and it did change some of the files successfully, yet it then errored and stopped:

```
 ERR PATH-TO-MY-COMPONENT.js Transformation error (Cannot read properties of undefined (reading 'length'))
TypeError: Cannot read properties of undefined (reading 'length')
    at NodePath.each 
   [...]
```

It throws the same error for almost all components and stops without processing them.

**Comment by mskelton** [comment]
What version of jscodeshift are you using?  Also, could you share a file that breaks?

**Comment by canpoyrazoglu** [comment]
While trying to reproduce a minimal example (I don't think I'm allowed to post the actual code due to NDA) I think I've pinpointed it:

If the component inherits props of another component's propType as is, I get the error.

File 1:
```
function BaseComponent() {
 [...]
}
BaseComponent.propTypes = { ... } // valid prop types
```

File 2:
```
function AnotherComponent() {
 [...]
}
AnotherComponent.propTypes = BaseComponent.propTypes;
```

Processing file 1 works. Processing file 2 fails with the error. If I copy and paste exact same prop types manually from file 1 to file 2 as `AnotherComponent.propTypes` it works.

```
jscodeshift: 0.11.0
 - babel: 7.16.5
 - babylon: 7.16.5
 - flow: 0.167.1
 - recast: 0.20.5
```

**Comment by canpoyrazoglu** [comment]
I see. If that's practically not possible to "import" it from another file, the best way to go is to keep it empty and move on to the next file.

If the processor has a "state" between processing different files, you might add something like preprocessing and finding/caching any prop types in all files (e.g. having an internal state of mapping "{ [BaseComponent.propTypes] = { ... }, [SomeComponent.propTypes]: { ... }, ... }"), _then_ start processing the actual changes. In that case, since all files are processed, BaseComponent.propTypes is already in this "cache" and in AnotherComponent file it can actually detect the reference to BaseComponent.propTypes and process accordingly.

If that's too much work or not feasible for any reason, a nice informational message like "BaseComponent.propTypes was not found in AnotherComponent.js file. If that file exists in another file that is unsupported." might be helpful.

Regardless, thanks for the nice script in its current form, just know that you've saved me a nice deal of time _even with the errors_!
